version: '3.4'

services:
  backend:
    image: backend
    build:
      context: Backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 5700
    ports:
      - 5700:6700
